config/routes.rb
MobileGullakApp::Application.routes.draw do

resources :viewed_offers

 resources :ratings do
    collection do
      get :rating_app
    end
  end

  resources :availed_offers do 
    collection do
      get :customer_availed_offer,:loyalty_profile
    end
  end

  resources :customers do
    collection do
      get :register_customer, :modify_profile,:customer_location,:listing_locations
    end
  end

  get "pages/create_user_using_app","pages/create_company_location", "pages/loyalty_benefits","pages/users_details","pages/user_bssid","pages/checkin_offer","pages/merchant_details","pages/loyalty_profile"
  get "loyalties/edit_loyalty_benefits","loyalties/close_loyalty_profile","loyalties/closed_loyalty","loyalties/loyalty_performance","loyalties/merchant_mac","loyalties/merchant_login"

  devise_for :users

  #mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  namespace :admin do

    resources :companies do
      member do
        get :manage
      end
      collection do
        get :autocomplete_search
      end
    end

    resources :plans
    resources :users do
      member do
        post :invite
      end
    end
    resources :subscriptions do
      member do
        put :close
      end
    end

    get :dashboard, to: 'panels#dashboard'
    get :configuration, to: 'panels#configuration'
    get :api, to: 'panels#api'

    root :to => 'panels#dashboard'
  end

  resources :merchants, :only => [] do
    member do
      get :dashboard
      get :reports
      get :campaigns
      get :my_account
    end
  end

  resources :companies, :path => :merchants, :only => [] do
    resources :loyalties, :shallow => true
    resources :offers, :shallow => true do
      member do
        put :close
        get :report        
      end
    end
  end

  resources :companies, :only => [:edit, :update] do
    resources :locations
  end

  root 'pages#home'

  namespace :api do
    namespace :v1, :defaults => {:format => 'json'} do
      resources :deals , only: [:index, :show] do
        member do
          post :view
          post :claim
        end
        collection do
          get :search
        end
      end
      resources :locations , only: [:index, :show] do
        collection do
          get :near
        end
      end
      resources :companies, only: [:index] do
      end
    end
    get "*path" => 'api#bad_route'
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :users, :dependent => :delete_all
  has_many :subscriptions, :dependent => :delete_all
  has_many :offers, :dependent => :delete_all
  has_many :locations, :dependent => :delete_all
  has_many  :loyalties#,:dependent => :delete_all
  belongs_to :category

  validates :name, presence: true

  has_attached_file :logo

  def self.search(search, page)
    search ||= ''
    paginate :per_page => 5, :page => page, :conditions => ['lower(companies.name) like ?', "%#{search.downcase}%"], :order => 'lower(companies.name)'
  end

  def subscription
    self.subscriptions.order(:created_at).last
  end

  def has_active_subscription?
    s = subscription
    s and s.is_valid?
  end

  def active_offers
    offers.open
  end

  def max_active_offers
    if has_active_subscription?
      subscription.plan.active_offers
    else
      0
    end
  end

  def last_sign_in_at
    u = self.users.order("current_sign_in_at desc").first
    u.last_sign_in_at if u
  end

end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::Controller
  before_filter :authenticate_user!
  before_action :set_company, only: [:show, :edit, :manage, :update, :destroy]

  def autocomplete_search
    companies = Company.search(params[:name], 1)
    render json: companies.collect{ |t| { value: t.name } }
  end

  # GET /companies/1/manage
  def manage
  end

  # GET /companies
  def index
    @companies = Company.all
  end

  # GET /companies/1
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to manage_admin_company_url(@company), notice: 'Company was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to admin_dashboard_url, notice: 'Company was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
    redirect_to admin_dashboard_url, notice: 'Company was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def company_params
      params.require(:company).permit!
    end
end

app/controllers/api/v1/companies_controller.rb
class Api::V1::CompaniesController < Api::ApiController

  respond_to :json

  before_action :set_pagination, :only => [:index]

  #parameters:
  #  phone,
  #  category,
  #pagination parameters:
  #  limit,
  #  offset
  def index

    companies = Company.limit(@limit).offset(@offset)

    if params[:phone].present?
      companies = companies.where(:phone => params[:phone])
    end

    respond_with companies
  end

  def show
    render :json => Company.find(params[:id])
  end

  private


  # Only allow a trusted parameter "white list" through.
  #def deals_params
  #  params.permit(:company_id, :location_id, :category, :limit, :offset, :format)
  #end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!
  before_action do
    set_company(params[:id])
  end

  # GET /companies/1/edit
  def edit
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      redirect_to my_account_merchant_url(@company), notice: 'Company was successfully updated.'
    else
      render action: 'edit'
    end
  end

  private
    # Only allow a trusted parameter "white list" through.
    def company_params
      params.require(:company).permit!
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/admin/companies/_form.html.erb
<%= simple_form_for([:admin, @company], :html => { :class => 'form-horizontal', :multipart => true }) do |f| %>
    <div class="row">
      <div class="span6">
        <%= f.input :name %>
        <%= f.input :phone,label: 'Mobile Number' %>
        <%= f.input :website %>
        <%= f.input :username %>
        <%= f.input :pwd, label: 'Password' %>
	<%= f.input :email %>
        <%= f.input :fb_address %>
        <%= f.input :bssid %>
        <%= f.input :description, :input_html => { :rows => 5, :style => "width: 500px"}  %>
        <%= f.association :category %>
      </div>
      <div class="span4">
        <%= f.file_field :logo %>
      </div>
    </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_dashboard_url, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/companies/edit.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/companies/index.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:website) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.id, admin_company_path(company) %></td>
        <td><%= company.name %></td>
        <td><%= company.website %></td>
        <td><%= company.phone %></td>
        <td><%= company.description %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_company_path(company), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_company_path(company),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_company_path,
            :class => 'btn btn-primary' %>

app/views/admin/companies/manage.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%= @company.name %></h1>
  <% if @company.logo.exists? %>
      <%= image_tag @company.logo.url(:thumb) %>
  <% end %>
</div>


<div class="row">
	<!--<div class="span4">
		<table class="table">
			<thead>
				<tr>
					<th colspan="2">Subscription</th>
				</tr>
			</thead>
			<tbody>
            <% if @company.subscription && @company.subscription.is_valid?  %>
				<tr>
					<td>Plan</td>
					<td><%= @company.subscription.plan.name %></td>
				</tr>
				<tr>
					<td>Expires at</td>
					<td><%= l @company.subscription.expires_at.to_date %></td>
				</tr>
                <tr>
                  <td><%= link_to 'Edit Subscription', edit_admin_subscription_path(@company.subscription), :class => 'btn' %></td>
                  <td><%= link_to 'Close Subscription', close_admin_subscription_path(@company.subscription), :method => 'put', :class => 'btn btn-danger'%></td>
                </tr>

            <% else %>
                <tr>
                  <td colspan="2">
                    <%= link_to 'Create Subscription', new_admin_subscription_path(:company_id => @company.id), :class => 'btn' %>
                  </td>
                </tr>
            <% end %>
			</tbody>
		</table>
	</div>----->

	<div class="span8">
		<table class="table" width="100%">
			<thead>
				<!--<tr>
					<th colspan="4">Users</th>
				</tr>-->
				<tr>
					<td>Name</td>
					<td>Email</td>
					<!--<td>API Token</td>-->
					<td>Mobile Number</td>
					<td>Website</td>
					<td>Username</td>
					<td>Password</td>
					<td>Facebook Address</td>
					<td>BSSID</td>
					<td>Description</td>
					<td>Category</td>
                    <td>&nbsp;</td>
				</tr>
			</thead>
			<tbody>
           
	<% if @company.name.empty? %>
                <tr>
                  <td colspan="4">
                    Empty.
                  </td>
                </tr>
            <% end %>
           
		<tr>
					<td><%= @company.name %><td>
					<td><%= @company.email %></td>
					<td><%= @company.phone %></td>
					<td><%= @company.website %></td>
					<td><%= @company.username %></td>
					<td><%= @company.pwd %></td>
					<td><%= @company.fb_address %></td>
					<td><%= @company.bssid %></td>
					<td><%= @company.description %></td>
					<td><%= @company.category.nil? ? '': @company.category.name %></td>
					<td>
                      <div class="btn-group">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                          <i class="icon-cog"></i>
                          <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                          <li>
				<!-- <%#= link_to edit_admin_user_path(u) do %> -->
                            <%= link_to edit_admin_company_path(@company) do %>                           
                                <i class="icon-edit"></i>
                                Edit
                            <% end %>
                          </li>
                          <li>
                            <%= link_to admin_company_path(@company), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you :sure?')) } do %>
                                <i class="icon-remove"></i>
                                Delete
			    <% end %>
	                 </li>
                        </ul>
                      </div>

					</td>
				</tr>
	</tbody>
		</table>
	  </div>

</div>

app/views/admin/companies/new.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/companies/show.html.erb
<%- model_class = Company -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="row">

	<div class="span4">
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @company.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:website) %>:</strong></dt>
  <dd><%= @company.website %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @company.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @company.description %></dd>
</dl>

</div>
<div class="span4">
    <% if @company.logo.exists? %>
	<%= image_tag @company.logo.url(:thumb) %>
    <% end %>
</div>

</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_companies_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_company_path(@company), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_company_path(@company),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>