config/routes.rb
MobileGullakApp::Application.routes.draw do

resources :viewed_offers

 resources :ratings do
    collection do
      get :rating_app
    end
  end

  resources :availed_offers do 
    collection do
      get :customer_availed_offer,:loyalty_profile
    end
  end

  resources :customers do
    collection do
      get :register_customer, :modify_profile,:customer_location,:listing_locations
    end
  end

  get "pages/create_user_using_app","pages/create_company_location", "pages/loyalty_benefits","pages/users_details","pages/user_bssid","pages/checkin_offer","pages/merchant_details","pages/loyalty_profile"
  get "loyalties/edit_loyalty_benefits","loyalties/close_loyalty_profile","loyalties/closed_loyalty","loyalties/loyalty_performance","loyalties/merchant_mac","loyalties/merchant_login"

  devise_for :users

  #mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  namespace :admin do

    resources :companies do
      member do
        get :manage
      end
      collection do
        get :autocomplete_search
      end
    end

    resources :plans
    resources :users do
      member do
        post :invite
      end
    end
    resources :subscriptions do
      member do
        put :close
      end
    end

    get :dashboard, to: 'panels#dashboard'
    get :configuration, to: 'panels#configuration'
    get :api, to: 'panels#api'

    root :to => 'panels#dashboard'
  end

  resources :merchants, :only => [] do
    member do
      get :dashboard
      get :reports
      get :campaigns
      get :my_account
    end
  end

  resources :companies, :path => :merchants, :only => [] do
    resources :loyalties, :shallow => true
    resources :offers, :shallow => true do
      member do
        put :close
        get :report        
      end
    end
  end

  resources :companies, :only => [:edit, :update] do
    resources :locations
  end

  root 'pages#home'

  namespace :api do
    namespace :v1, :defaults => {:format => 'json'} do
      resources :deals , only: [:index, :show] do
        member do
          post :view
          post :claim
        end
        collection do
          get :search
        end
      end
      resources :locations , only: [:index, :show] do
        collection do
          get :near
        end
      end
      resources :companies, only: [:index] do
      end
    end
    get "*path" => 'api#bad_route'
  end

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :customer
  belongs_to :user
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user! ,:except => [:rating_app]

  # GET /ratings
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  def create
    @rating = Rating.new(rating_params)

    if @rating.save
      redirect_to @rating, notice: 'Rating was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /ratings/1
  def update
    if @rating.update(rating_params)
      redirect_to @rating, notice: 'Rating was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /ratings/1
  def destroy
    @rating.destroy
    redirect_to ratings_url, notice: 'Rating was successfully destroyed.'
  end
  
  def rating_app #customer will rate app against merchant's name
    @customer_id = params[:customer_id]
    @merchant_id =  params[:merchant_id]
    @rating =  params[:rating]
    respond_to do |format|
      if request.format == 'json'
          unless @customer_id.nil?
            unless @merchant_id.nil?
              unless @rating.nil?
                  @customer = Customer.find_by(:id => @customer_id)
                  unless @customer.nil?
                    @merchant = User.find_by(:id => @merchant_id)
                      unless @merchant.nil?
                        @Rdone = Rating.find_by(:customer_id => @customer.id,:user_id => @merchant.id)                    
                        if @Rdone.nil?
                            @rate =  Rating.new(:customer_id => @customer.id,:user_id => @merchant.id,:rating => @rating)
                            @rate.save! 
                            if @rate.save
                              format.json {render :json => { :success => 'true',:message => 'Rating has been created successfully'}}
                            else
                              format.json {render :json => { :success => 'false',:message => 'Rating not saved',:error => @rate.errors.full_messages}}
                            end
                         else
                           @Rdone.update_column('rating',@rating)
                          format.json {render :json => { :success => 'false',:message => 'Rating has been updated successfully'}}
                         end
                       else
                        format.json {render :json => { :success => 'false',:message => 'Merchant ID does not exist'}}
                      end
                  else
                    format.json {render :json => { :success => 'false',:message => 'Customer ID does not exist'}}
                  end
              else
                format.json {render :json => { :success => 'false',:message => 'Rating cannot be blank'}}
              end
            else
              format.json {render :json => { :success => 'false',:message => 'Merchant cannot be blank'}}
            end
          else
            format.json {render :json => { :success => 'false',:message => 'Customer ID cannot be blank'}}
          end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def rating_params
      params.require(:rating).permit(:customer_id, :merchant_id, :rating)
    end
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer %><br>
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>User</th>
      <th>Rating</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.customer %></td>
        <td><%= rating.user %></td>
        <td><%= rating.rating %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @rating.customer %>
</p>

<p>
  <strong>Merchant:</strong>
  <%= @rating.user %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @rating.rating %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>