config/routes.rb
MobileGullakApp::Application.routes.draw do

resources :viewed_offers

 resources :ratings do
    collection do
      get :rating_app
    end
  end

  resources :availed_offers do 
    collection do
      get :customer_availed_offer,:loyalty_profile
    end
  end

  resources :customers do
    collection do
      get :register_customer, :modify_profile,:customer_location,:listing_locations
    end
  end

  get "pages/create_user_using_app","pages/create_company_location", "pages/loyalty_benefits","pages/users_details","pages/user_bssid","pages/checkin_offer","pages/merchant_details","pages/loyalty_profile"
  get "loyalties/edit_loyalty_benefits","loyalties/close_loyalty_profile","loyalties/closed_loyalty","loyalties/loyalty_performance","loyalties/merchant_mac","loyalties/merchant_login"

  devise_for :users

  #mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  namespace :admin do

    resources :companies do
      member do
        get :manage
      end
      collection do
        get :autocomplete_search
      end
    end

    resources :plans
    resources :users do
      member do
        post :invite
      end
    end
    resources :subscriptions do
      member do
        put :close
      end
    end

    get :dashboard, to: 'panels#dashboard'
    get :configuration, to: 'panels#configuration'
    get :api, to: 'panels#api'

    root :to => 'panels#dashboard'
  end

  resources :merchants, :only => [] do
    member do
      get :dashboard
      get :reports
      get :campaigns
      get :my_account
    end
  end

  resources :companies, :path => :merchants, :only => [] do
    resources :loyalties, :shallow => true
    resources :offers, :shallow => true do
      member do
        put :close
        get :report        
      end
    end
  end

  resources :companies, :only => [:edit, :update] do
    resources :locations
  end

  root 'pages#home'

  namespace :api do
    namespace :v1, :defaults => {:format => 'json'} do
      resources :deals , only: [:index, :show] do
        member do
          post :view
          post :claim
        end
        collection do
          get :search
        end
      end
      resources :locations , only: [:index, :show] do
        collection do
          get :near
        end
      end
      resources :companies, only: [:index] do
      end
    end
    get "*path" => 'api#bad_route'
  end

end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_filter :authenticate_user!
  before_action do
    set_company(params[:id])
  end

  def dashboard
    @stats = { :offers => Stats.offers_dashboard(@company), :redemptions => Stats.redemptions_dashboard(@company) }
  end

  def reports
    @offers = @company.offers.open
  end

  def campaigns
    @offers = @company.offers.closed
  end

  def my_account
  end

end

app/views/merchants/_offer.html.erb
<li class="span4 offer">

<div>

    <div class="span12 offer-caption ">
        <span class="validity"> OFFER VALID UNTIL <%= l offer.period_end.to_date %> </span>
        <div class="pull-right"><%= render :partial => 'offer_menu', :locals => { :offer => offer } %></div>
        <div class="offer-title"><%= offer.short_title %></div>
	</div>

    <div class="span12 offer-content">
        <div class="span3 pull-left">
            <% if offer.image.exists? %>
                <%= image_tag offer.image.url(:thumb) %>
            <% else %>
                <%= image_tag offer.company.logo.url(:thumb) %>
            <% end %>
        </div>

        <div class="span5 description">
            <%= offer.description %>
        </div>

        <% if offer.kind == 'percent_discount' %>
            <div class="span3 pull-right">
                <span class="offer-badge">-<%= offer.percent_discount %>%</span>
            </div>
        <% end %>
	</div>

    <div class="span12 offer-timetable">
        <%= render :partial => 'offer_timetable', :locals => {:offer => offer } %>
    </div>

    <div class="span12 offer-locations">
        <%= render :partial => 'offer_locations', :locals => { :offer => offer } %>
    </div>

</div>
</li>

app/views/merchants/_offer_locations.html.erb
<ul class="locations">
  <% offer.all_locations.each do |location| %>
    <li>
        <ul class="location">
          <li class="i1">
            <%= location.name %>
          </li>
          <li class="i2">
            <%= location.formatted_address %>
          </li>
          <li class="i3">
            <%= location.phone %>
          </li>
        </ul>
    </li>
  <% end %>
</ul>

app/views/merchants/_offer_menu.html.erb
<div class="btn-group pull-right">

  <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
    <i class="icon-cog"></i>
    <span class="caret"></span>
  </a>

  <ul class="dropdown-menu">
    <li>
      <%= link_to report_offer_path(offer) do %>
          <i class="icon-tasks"></i>
          Show Report
      <% end %>
    </li>
    <li>
      <%= link_to edit_offer_path(offer) do %>
          <i class="icon-edit"></i>
          Edit
      <% end %>
    </li>
    <li>
      <%= link_to close_offer_path(offer),
                  :method => :put,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure you want to close this offer?')) } do %>
          <i class="icon-remove"></i>
          Close
      <% end %>
    </li>
  </ul>
</div>

app/views/merchants/_offer_timetable.html.erb
<% unless offer.use_location_hours %>
    <% days = [:mon, :tue, :wed, :thu, :fri, :sat, :sun] %>
    <table>
      <thead>
        <tr>
          <% days.each do |d| %>
              <td width="14.25%"><%= d.to_s.upcase %></td>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% days.each do |d| %>
            <td><%= timetable_hour_range(offer.time_table, d) %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
<% end %>

app/views/merchants/campaigns.html.erb
<br>
<legend>Closed Offers</legend>
<table class="table">
	<thead>
	  <tr>
	    <th>Offer</th>
	    <th>Start Date</th>
	    <th>End Date</th>
	    <th>Duration</th>
	    <th>Viewed</th>
	    <th>Saved</th>
	    <th>Conversion</th>
          </tr>
        </thead>
	<tbody>
	<% @offers.each do |o| %>
             <!-- <% viewed = o.events.viewed.count %>
		<% claimed = o.claims.count %> -->
		<% viewed = ViewedOffer.find_by('offer_id =?',o.id).nil? ? 0 : ViewedOffer.where('offer_id =?',o.id).count %>
		<% claimed = AvailedOffer.find_by('offer_id =?',o.id).nil? ? 0 : AvailedOffer.where('offer_id =?',o.id).count %>
		<tr>
		  <td><%= o.short_title %></td>
		  <td><%= l o.period_start.to_date %></td>
		  <td><%= l o.period_end.to_date %></td>
		  <td><%= distance_of_time_in_words(o.period_start, o.period_end) %></td>
		  <td><%= viewed %></td>
		  <td><%= claimed %></td>
		  <% if claimed > viewed and claimed > 0 %>
			  <td>&gt;<%= number_to_percentage(1, :precision => 2) %></td>
		  <% elsif viewed != 0 %>
			  <td><%= number_to_percentage(claimed / viewed,  :precision => 2) %></td>
		  <% else %>
			  <td><%= number_to_percentage(0,  :precision => 2) %></td>
		  <% end %>
	<% end %>

	<% if @offers.empty? %>
		<tr><td colspan="7">Empty.</td></tr>
	<% end %>
	</tbody>
</table>

app/views/merchants/dashboard.html.erb
<div class="row">
  <div class="span4">
    <table class="table">
      <thead>
      <tr>
        <td>&nbsp;</td>
        <td>Last 7 Days</td>
        <td>Yesterday</td>
        <td>Today</td>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td>Offers</td>
        <% @stats[:offers][:total].each do |day, value| %>
            <td><%= value %></td>
        <% end %>
      </tr>
      <tr>
        <td><span class="label">Viewed</span></td>
        <% @stats[:offers][:viewed].each do |day, value| %>
            <td><%= value %></td>
        <% end %>
      </tr>
      <tr>
        <td><span class="label label-info">Claimed</span></td>
        <% @stats[:offers][:claimed].each do |day, value| %>
            <td><%= value %></td>
        <% end %>
      </tr>
      <tr>
        <td colspan="4">&nbsp;</td>
      </tr>
      </tbody>

      <tbody>
      <tr>
        <td>Redemption</td>
        <% @stats[:redemptions][:total].each do |day, value| %>
            <td><%= value %></td>
        <% end %>
      </tr>
      <tr>
        <td><span class="label">Viewed</span></td>
        <% @stats[:redemptions][:viewed].each do |day, value| %>
            <td><%= value %></td>
        <% end %>
      </tr>
      <tr>
        <td><span class="label label-info">Redeemed</span></td>
        <% @stats[:redemptions][:claimed].each do |day, value| %>
            <td><%= value %></td>
        <% end %>
      </tr>
    </table>
  </div>


  <div class="span4 offset2">
    <table class="table">
      <thead>
      <tr>
        <td>Subscription</td>
        <td>Valid Until</td>
      </tr>
      </thead>
      <tbody>
      <% if @company.subscription %>
          <tr>
            <td><%= @company.subscription.plan.name %></td>
            <td><%= l @company.subscription.expires_at.to_date %></td>
          </tr>
      <% else %>
          <tr>
            <td colspan="2">
              &mdash;
            </td>
          </tr>
      <% end %>

      </tbody>
    </table>
  </div>
</div>

<div id="offers-thumbs-section" class="row-fluid">
  <legend>Offers</legend>
  <ul class="thumbnails">
    <% @company.offers.open.each do |offer| %>
        <%= render :partial => 'offer', :locals => {:offer => offer} %>
    <% end %>
  </ul>
  <% if @company.offers.open.empty? %>
	  <p>Empty.</p>
  <% end %>

</div>

app/views/merchants/my_account.html.erb
<h1><%= @company.name %></h1>

<div class="row">
  <div class="span3">
    <table class="table">
    <tbody>
        <tr>
          <td>Category</td>
          <td><%= @company.category.name if @company.category %></td>
        </tr>
        <tr>
          <td>Website</td>
          <td><%= @company.website %></td>
        </tr>
        <tr>
          <td>Phone</td>
          <td><%= @company.phone %></td>
        </tr>
        <% if @company.logo.exists? %>
        <tr>
          <td colspan="2">
            <%= image_tag @company.logo.url(:medium) %>
          </td>
        </tr>
        <% end %>
        <tr>
          <td colspan="2">
            Description
            <br/>
            <%= @company.description %>
          </td>
        </tr>
       <!-- <% if @company.subscription && @company.subscription.is_valid?  %>
        <tr>
          <td>Subscription</td>
          <td><%= @company.subscription.plan.name %></td>
        </tr>
        <tr>
          <td>Valid until</td>
          <td><%= l @company.subscription.expires_at.to_date %></td>
        </tr>
        <% else %>
        <tr>
          <td>Subscription</td>
          <td>&mdash;</td>
        </tr>
        <% end %>-->
    </tbody>
    </table>
    <%= link_to 'Edit', edit_company_path(@company), :class => 'btn' %>
  </div>

  <div class="span8 offset1">
	<div class="text-center">
		<% if @company.locations.empty? %>
		        <%= image_tag 'http://placehold.it/600x400&text=No++Locations+yet.' %>
		<% else %>	
			<%= image_tag static_gmap_url(600, 400, @company.locations) %>
		<% end %>
	</div>
    <br/>
    <br/>
    <table class="table">
      <thead>
        <caption>Locations</caption>
        <tr>
          <th>&nbsp;</th>
          <th>Name</th>
          <th>Street</th>
          <th>Zip</th>
          <th>City</th>
          <th>Region</th>
          <th>Offers</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
          <% @company.locations.each_with_index do |location, i| %>
              <tr>
    	        <td><span class="badge badge-important"><%= i + 1 %></span></td>
		<td><%= location.name %></td>
                <td><%= location.street_address %></td>
                <td><%= location.zipcode %></td>
                <td><%= location.city %></td>
                <td><%= location.region %></td>
		<td><%= location.offers_total_count %></td>
		<td>
		<div class="btn-group">
			<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
				<i class="icon-cog"></i>
				<span class="caret"></span>
			</a>
			<ul class="dropdown-menu">
				<li>
					<%= link_to edit_company_location_path(@company, location) do %>
					<i class="icon-edit"></i>
					Edit
					<% end %>
				</li>
				<li>
					<%= link_to company_location_path(@company, location), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you :sure?')) } do %>
					<i class="icon-remove"></i>
					Delete
					<% end %>
				</li>
			</ul>
		</div>
		</td>
              </tr>
          <% end %>
      </tbody>
    </table>
    <%= link_to 'Add Location', new_company_location_path(@company), :class => 'btn' %>
  </div>

</div>

app/views/merchants/reports.html.erb
<br>
<legend>Open Offers</legend>
<table class="table">
	<thead>
	  <tr>
	    <th>Offer</th>
	    <th>Start Date</th>
	    <th>End Date</th>
	    <th>Duration</th>
	    <th>Viewed</th>
	    <th>Saved</th>
	    <th>Conversion</th>	    
          </tr>
        </thead>
	<tbody>
	<% @offers.each do |o| %>
             <!-- <% viewed = o.events.viewed.count %>
		<% claimed = o.claims.count %> -->
		<% viewed = ViewedOffer.find_by('offer_id =?',o.id).nil? ? 0 : ViewedOffer.where('offer_id =?',o.id).count %>
		<% claimed = AvailedOffer.find_by('offer_id =?',o.id).nil? ? 0 : AvailedOffer.where('offer_id =?',o.id).count %>

		<tr>
		  <td><%= link_to o.short_title, report_offer_path(o) %></td>
		  <td><%= l o.period_start.to_date %></td>
		  <td><%= l o.period_end.to_date %></td>
		  <td><%= distance_of_time_in_words(o.period_start, o.period_end) %></td>
		  <td><%= viewed %></td>
		  <td><%= claimed %></td>
		  <% if claimed > viewed and claimed > 0 %>
			  <td>&gt;<%= number_to_percentage(1, :precision => 2) %></td>
		  <% elsif viewed != 0 %>
			  <td><%= number_to_percentage(claimed / viewed,  :precision => 2) %></td>
		  <% else %>
			  <td><%= number_to_percentage(0,  :precision => 2) %></td>
		  <% end %>
	<% end %>
	<% if @offers.empty? %>
		<tr><td colspan="7">Empty.</td></tr>
	<% end %>

	</tbody>
</table>