config/routes.rb
MobileGullakApp::Application.routes.draw do

resources :viewed_offers

 resources :ratings do
    collection do
      get :rating_app
    end
  end

  resources :availed_offers do 
    collection do
      get :customer_availed_offer,:loyalty_profile
    end
  end

  resources :customers do
    collection do
      get :register_customer, :modify_profile,:customer_location,:listing_locations
    end
  end

  get "pages/create_user_using_app","pages/create_company_location", "pages/loyalty_benefits","pages/users_details","pages/user_bssid","pages/checkin_offer","pages/merchant_details","pages/loyalty_profile"
  get "loyalties/edit_loyalty_benefits","loyalties/close_loyalty_profile","loyalties/closed_loyalty","loyalties/loyalty_performance","loyalties/merchant_mac","loyalties/merchant_login"

  devise_for :users

  #mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  namespace :admin do

    resources :companies do
      member do
        get :manage
      end
      collection do
        get :autocomplete_search
      end
    end

    resources :plans
    resources :users do
      member do
        post :invite
      end
    end
    resources :subscriptions do
      member do
        put :close
      end
    end

    get :dashboard, to: 'panels#dashboard'
    get :configuration, to: 'panels#configuration'
    get :api, to: 'panels#api'

    root :to => 'panels#dashboard'
  end

  resources :merchants, :only => [] do
    member do
      get :dashboard
      get :reports
      get :campaigns
      get :my_account
    end
  end

  resources :companies, :path => :merchants, :only => [] do
    resources :loyalties, :shallow => true
    resources :offers, :shallow => true do
      member do
        put :close
        get :report        
      end
    end
  end

  resources :companies, :only => [:edit, :update] do
    resources :locations
  end

  root 'pages#home'

  namespace :api do
    namespace :v1, :defaults => {:format => 'json'} do
      resources :deals , only: [:index, :show] do
        member do
          post :view
          post :claim
        end
        collection do
          get :search
        end
      end
      resources :locations , only: [:index, :show] do
        collection do
          get :near
        end
      end
      resources :companies, only: [:index] do
      end
    end
    get "*path" => 'api#bad_route'
  end

end

app/controllers/admin/panels_controller.rb
class Admin::PanelsController < Admin::Controller
  before_filter :authenticate_user!
  def dashboard
    @companies = Company.search(params[:search], params[:page])
    @stats = Stats.company_dashboard_last_five_weeks
  end

  def configuration
    @plans = Plan.all
    @admins = User.where(:admin => true)
  end

  def api

  end

end

app/views/admin/panels/api.html.erb
<h1>API</h1><br/><p>Examples using curl:<ul>	<li> "curl -u API_TOKEN: HOST/api/v1/deals" </li>	<li> "curl -u API_TOKEN: HOST/api/v1/deals/1" </li>	<li> "curl -u API_TOKEN: HOST/api/v1/locations/near?latitude=52.3723061585724&longitude=4.90190997719765&radius=5" </li>	<li> "curl -u API_TOKEN: HOST/api/v1/locations/1" </li>    <li> "curl -u API_TOKEN: --data "user_ref=joe@mail.com" "HOST/api/v1/deals/1/claim" </li></ul><br/><br/><iframe src="/apiv1.html" frameBorder="0" width="100%" height="500"></iframe>

app/views/admin/panels/dashboard.html.erb
<div class="row">
	<div class="span6">
<table class="table">
	<thead>
		<tr>
			<th rowspan="2">Week</th>
			<% @stats[0][:data].each do |k, v| %>
				<th><%= Date.parse(k).strftime("%W") %></th>
			<% end %>
		</tr>
		<tr>
			<% @stats[0][:data].each do |k, v| %>
				<th><%= Date.parse(k).strftime("%e %b") %> - <%= (Date.parse(k) + 1.week).strftime("%e %b") %></th>
			<% end %>
		</tr>
	</thead>
	<tbody>
		<% @stats.each do |s| %>
			<tr>
				<td><%= s[:label] %></td>
				<% s[:data].each do |k,v|  %>
					<td><%= v %></td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>
	</div>
	<div class="span6">
		<%= line_chart @stats, :library => {:curveType => 'none'} %>
	</div>
</div>

<br/>
<br/>
<br/>
<br/>

<div class="well">

<%= form_tag request.path, :method => 'get', :class => "form-search"  do %>
	<%= text_field_tag :search, params[:search], :placeholder => 'Search by name', :class => 'input-medium search-query with_autocomplete', 'data-autocompleteurl' => autocomplete_search_admin_companies_path %>
    <%= hidden_field_tag :page, 1 %>
	<%= link_to 'New Company',
		new_admin_company_path,
		:class => 'btn  pull-right' %>
<% end %>


</div>

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Locations</th>
			<th>Offers</th>
			<th>Joined</th>
            <th>#Users</th>
			<th>Last Login</th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	<tbody>
		<% @companies.each do |c| %>
		<tr>
			<td><%= c.name %></td>
			<td><%= c.locations.length %></td>
			<td><%= c.offers.length %> </td>
			<td><%= l c.created_at.to_date %></td>
            <td><%= c.users.length %></td>
            <td><%= c.last_sign_in_at.nil?? '-': l(c.last_sign_in_at) %></td>
			<td>&nbsp;</td>
			<td>
				<div class="btn-group">
					<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="icon-cog"></i>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li>
						<%= link_to edit_admin_company_path(c) do %>
							<i class="icon-edit"></i>
							Edit 
						<% end %>
						</li>
						<li>
						<%= link_to manage_admin_company_path(c) do %>
							<i class="icon-wrench"></i>
							Manage
						<% end %>
						</li>
                        <li>
                        <%= link_to admin_company_path(c),
                                  :method => :delete,
                                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } do %>
							<i class="icon-remove"></i>
							Delete
						<% end %>
						</li>
						<li>
						<%= link_to my_account_merchant_path(c) do %>
							<i class="icon-arrow-right"></i>
							Merchant's Panel
						<% end %>
						</li>
					</ul>
				</div>
			</td>
		<% end %>
		</tr>
	</tbody>

</table>


<%= will_paginate @companies, renderer: BootstrapPagination::Rails %>